## Basic configuration
naming: "color_line" # the name of this model. Determine the path to save checkpoint and events file.
model_path: models  # root path to save checkpoint and events file. The final path would be <model_path>/<naming>

train_dir: 2014_COCO_train #directory for COCO dataset train dataset
## Weight of the loss
content_weight: 1.0  # weight for content features loss
tv_weight: 0.0  # weight for total variation loss

## The size, the iter number to run
image_size: 256
batch_size: 4
epoch: 2

## Loss Network
loss_model: "vgg_16"
content_layers:  # use these layers for content loss
  - "vgg_16/conv3/conv3_3"
  - "vgg_16/conv4/conv4_3"
checkpoint_exclude_scopes: "vgg_16/fc"  # we only use the convolution layers, so ignore fc layers.
loss_model_file: "pretrained/vgg_16.ckpt"  # the path to the checkpoint
