## Basic configuration
naming: "super_resolution" # the name of this model. Determine the path to save checkpoint and events file.
model_path: models  # root path to save checkpoint and events file. The final path would be <model_path>/<naming>

train_dir: train2014 #directory for COCO dataset train dataset
train_dataset_size: 10000
## Weight of the loss
content_weight: 1.0  # weight for content features loss
tv_weight: 0.0  # weight for total variation loss

## The size, the iter number to run
image_size: 288
image_scale: 4 #low resolution size for scale factor
batch_size: 4
epoch: 80

## Loss Network
loss_model: "vgg_16"
content_layers:  # use these layers for content loss
  - "vgg_16/conv2/conv2_2"
checkpoint_exclude_scopes: "vgg_16/fc"  # we only use the convolution layers, so ignore fc layers.
loss_model_file: "pretrained/vgg_16.ckpt"  # the path to the checkpoint
